Update build

diff --git a/commands/build b/commands/build
--- a/commands/build
+++ b/commands/build
@@ -1,34 +1,42 @@
-path_commands=`pwd`
+current_path=`pwd`
+path_commands="`dirname \"$0\"`"
+path_commands="`( cd \"$path_commands\" && pwd )`"
+if [ -z "$path_commands" ] ; then
+    echo "Error"
+    exit 1  # fail
+else
+    rm -f ${path_commands}/../log/build.log
 
-rm -f ${path_commands}/../log/build.log
+    cd ${path_commands}/../
 
-cd ${path_commands}/../
+    if [ ! -e "delivery/keystore/grabmanga.keystore" ]
+    then
+        rm -Rf delivery
+        mkdir -p delivery/keystore
+        cd delivery/keystore
+        keytool -genkey -v -keystore grabmanga.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
+    fi
 
-if [ ! -e "delivery/keystore/grabmanga.keystore" ]
-then
-    rm -Rf delivery
-    mkdir -p delivery/keystore
-    cd delivery/keystore
-    keytool -genkey -v -keystore grabmanga.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
+    cd ${path_commands}/../
+
+    if [ ! -d platforms/android ]
+    then
+        cordova platform add android >> log/build.log
+    fi
+
+    cordova build --release >> log/build.log
+
+    cd ${path_commands}/../platforms/android/build/outputs/apk
+
+    jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${path_commands}/../delivery/keystore/grabmanga.keystore android-release-unsigned.apk alias_name >> ${path_commands}/../log/build.log
+
+    if [ -f ${path_commands}/../delivery/GrabManga.apk ]
+    then
+        date=`date '+%Y-%m-%d_%H%M%S'`
+        mv -f ${path_commands}/../delivery/GrabManga.apk ${path_commands}/../delivery/GrabManga_${date}.apk
+    fi
+
+    mv -f ${path_commands}/../platforms/android/build/outputs/apk/android-release-unsigned.apk ${path_commands}/../delivery/GrabManga.apk
 fi
 
-cd ${path_commands}/../
-
-if [ ! -d platforms/android ]
-then
-    cordova platform add android >> ${path_commands}/../log/build.log
-fi
-
-cordova build --release >> ${path_commands}/../log/build.log
-
-cd ${path_commands}/../platforms/android/build/outputs/apk
-
-jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ${path_commands}/../delivery/keystore/grabmanga.keystore android-release-unsigned.apk alias_name >> ${path_commands}/../log/build.log
-
-if [ -f ${path_commands}/../delivery/GrabManga.apk ]
-then
-    date=`date '+%Y-%m-%d_%H%M%S'`
-    mv -f ${path_commands}/../delivery/GrabManga.apk ${path_commands}/../delivery/GrabManga_${date}.apk
-fi
-
-mv -f ${path_commands}/../platforms/android/build/outputs/apk/android-release-unsigned.apk ${path_commands}/../delivery/GrabManga.apk
+cd $current_path
