maj all command scripts for good execution path

diff --git a/commands/generateKeystore b/commands/generateKeystore
--- a/commands/generateKeystore
+++ b/commands/generateKeystore
@@ -1,6 +1,15 @@
 current_path=`pwd`
-rm -Rf ${current_path}/../delivery
-mkdir ${current_path}/../delivery
-mkdir ${current_path}/../delivery/keystore
-cd ${current_path}/../delivery/keystore
-keytool -genkey -v -keystore grabmanga.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
+path_commands="`dirname \"$0\"`"
+path_commands="`( cd \"$path_commands\" && pwd )`"
+if [ -z "$path_commands" ] ; then
+    echo "Error"
+    exit 1  # fail
+else
+    cd $path_commands/../
+    rm -Rf delivery
+    mkdir -p delivery/keystore
+    cd delivery/keystore
+    keytool -genkey -v -keystore grabmanga.keystore -alias alias_name -keyalg RSA -keysize 2048 -validity 10000
+fi
+
+cd $current_path
diff --git a/commands/run b/commands/run
--- a/commands/run
+++ b/commands/run
@@ -1,5 +1,15 @@
-echo "Application launched, please waiting 15-20s"
-echo ""
-echo "Ctrl+C to cancel"
+current_path=`pwd`
+exec_path="`dirname \"$0\"`"
+exec_path="`( cd \"$exec_path\" && pwd )`"
+if [ -z "$exec_path" ] ; then
+    echo "Error"
+    exit 1  # fail
+else
+    echo "Application launched, please waiting 15-20s"
+    echo ""
+    echo "Ctrl+C to cancel"
+    cd $exec_path/../
+    ionic serve >> log/serve.log
+fi
 
-ionic serve >> log/serve.log
+cd $current_path
